# Welcome to Jekyll!

theme: jekyll-theme-chirpy

# Website settings
title: Impassive
description: Impassive's blog
baseurl:  / # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://yangbiny.github.io/yangbiny.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /yangbiny.github.io/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Impassive  # Be used at blog posts' author.
  first_name: Impassive  # Be used at index page about me section.
  last_name:  # Be used at index page about me section.
  avatar: /img/title.jpeg  # upload your avatar at directory and edit it.
  github_username: yangbiny  # Leave blank if you don't have now
  linkedin_id:  # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: impassive@aliyun.com  # Leave blank if you don't have now
  cv: https://github.com/yangbiny  # An online CV can be printed as PDF, leave blank if you don't have now
  desc: 一个平平无奇的打工人.  # Describe yourself.

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
# id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: off  # index page carousel switch
blog_carousel: off  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settingss
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
